gitops-runtime:
  app-proxy:
    config:
      cors: https://hermes-onprem-test.cf-op.com
  global:
    codefresh:
      accountId: 6932d36a140ddf89c7c31dfc
      url: https://hermes-onprem-test.cf-op.com
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
      ingress:
        className: nginx-internal
        enabled: true
        hosts:
          - alina-hermes.rnd-sandbox.cf-infra.com
        protocol: https
      name: test-date
      isConfigurationRuntime: true
  installer:
    skipValidation: true
